{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": 1,
   "metadata": {},
   "outputs": [],
   "source": [
    "import pandas as pd\n",
    "import streamlit as st\n",
    "from urllib.request import urlopen\n",
    "from PIL import Image\n",
    "from json2html import *\n",
    "import json\n",
    "from query import SnowLoader, Query\n",
    "st.set_page_config(layout=\"wide\")\n",
    "image = Image.open('./assets/os_logo.jpg')"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 2,
   "metadata": {},
   "outputs": [
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "2022-11-29 18:27:53.767 INFO    snowflake.connector.connection: Snowflake Connector for Python Version: 2.7.11, Python Version: 3.8.13, Platform: macOS-10.16-x86_64-i386-64bit\n",
      "2022-11-29 18:27:53.767 INFO    snowflake.connector.connection: This connection is in OCSP Fail Open Mode. TLS Certificates would be checked for validity and revocation status. Any other Certificate Revocation related exceptions or OCSP Responder failures would be disregarded in favor of connectivity.\n",
      "2022-11-29 18:27:53.768 INFO    snowflake.connector.connection: Setting use_openssl_only mode to False\n",
      "2022-11-29 18:27:57.072 INFO    snowflake.connector.cursor: query: [select * from ds_dev_database.influencer.product_release]\n",
      "2022-11-29 18:27:58.287 INFO    snowflake.connector.cursor: query execution done\n",
      "2022-11-29 18:27:58.293 INFO    snowflake.connector.cursor: query: [select * from ds_dev_database.influencer.creator]\n",
      "2022-11-29 18:27:59.673 INFO    snowflake.connector.cursor: query execution done\n"
     ]
    }
   ],
   "source": [
    "ob = SnowLoader()\n",
    "releases = ob.run('''select * from ds_dev_database.influencer.product_release''')\n",
    "release_dict = releases.set_index('STARTS_AT')['ID'].to_dict()\n",
    "creators = ob.run('''select * from ds_dev_database.influencer.user_profile_info''').set_index('INFLUENCER_HANDLE')\n",
    "\n",
    "influ_select_from_list = list(creators.index)\n",
    "release_select_from_list = list(release_dict.keys())"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 19,
   "metadata": {},
   "outputs": [],
   "source": [
    "influ_chk = influ_select_from_list[0]\n",
    "release_chk = release_select_from_list[2]"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 20,
   "metadata": {},
   "outputs": [
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "2022-11-29 18:31:14.922 INFO    snowflake.connector.cursor: query: [with drops as ( select m.creator_id, m.discount_percentage, m.assignment, m.sort...]\n",
      "2022-11-29 18:31:15.145 INFO    snowflake.connector.cursor: query execution done\n"
     ]
    }
   ],
   "source": [
    "dat = Query.get_drop(ob, influ_chk, release_dict[release_chk])"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 21,
   "metadata": {},
   "outputs": [
    {
     "data": {
      "text/html": [
       "<div>\n",
       "<style scoped>\n",
       "    .dataframe tbody tr th:only-of-type {\n",
       "        vertical-align: middle;\n",
       "    }\n",
       "\n",
       "    .dataframe tbody tr th {\n",
       "        vertical-align: top;\n",
       "    }\n",
       "\n",
       "    .dataframe thead th {\n",
       "        text-align: right;\n",
       "    }\n",
       "</style>\n",
       "<table border=\"1\" class=\"dataframe\">\n",
       "  <thead>\n",
       "    <tr style=\"text-align: right;\">\n",
       "      <th></th>\n",
       "      <th>CREATOR_ID</th>\n",
       "      <th>DISCOUNT_PERCENTAGE</th>\n",
       "      <th>ASSIGNMENT</th>\n",
       "      <th>SORT_ORDER</th>\n",
       "      <th>PRODUCT_ID</th>\n",
       "      <th>COLLAB_METADATA</th>\n",
       "      <th>IMAGEURL</th>\n",
       "      <th>PRODUCT_GROSS_MARGIN</th>\n",
       "      <th>BREAKEVEN_DISCOUNT_PCT</th>\n",
       "      <th>MAX_CLAIMED_COUNT</th>\n",
       "      <th>GENDER_CLEANED</th>\n",
       "      <th>PRICE</th>\n",
       "      <th>PRODUCT_TITLE</th>\n",
       "      <th>OS_MERCHANT</th>\n",
       "      <th>STATUS</th>\n",
       "    </tr>\n",
       "  </thead>\n",
       "  <tbody>\n",
       "    <tr>\n",
       "      <th>10</th>\n",
       "      <td>chelseaericasmith</td>\n",
       "      <td>0.2</td>\n",
       "      <td>Test Drop 10 drops w/ cogs</td>\n",
       "      <td>0</td>\n",
       "      <td>114589574</td>\n",
       "      <td>None</td>\n",
       "      <td>https://cdn.shopify.com/s/files/1/0200/5278/pr...</td>\n",
       "      <td>0.271190</td>\n",
       "      <td>0.271190</td>\n",
       "      <td>420.0</td>\n",
       "      <td>U</td>\n",
       "      <td>1599.99</td>\n",
       "      <td>10\" Organic Latex Mattress</td>\n",
       "      <td>Spindle Mattress</td>\n",
       "      <td>scroll</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>11</th>\n",
       "      <td>chelseaericasmith</td>\n",
       "      <td>1.0</td>\n",
       "      <td>Test Drop 10 drops w/ cogs</td>\n",
       "      <td>0</td>\n",
       "      <td>114589574</td>\n",
       "      <td>None</td>\n",
       "      <td>https://cdn.shopify.com/s/files/1/0200/5278/pr...</td>\n",
       "      <td>0.271190</td>\n",
       "      <td>0.271190</td>\n",
       "      <td>420.0</td>\n",
       "      <td>U</td>\n",
       "      <td>1599.99</td>\n",
       "      <td>10\" Organic Latex Mattress</td>\n",
       "      <td>Spindle Mattress</td>\n",
       "      <td>scroll</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>12</th>\n",
       "      <td>chelseaericasmith</td>\n",
       "      <td>1.0</td>\n",
       "      <td>Test Drop 10 drops w/ cogs</td>\n",
       "      <td>1</td>\n",
       "      <td>4703793545353</td>\n",
       "      <td>{\"descriptions\":[{\"icon\": \"camera\",\"text\":\"1 R...</td>\n",
       "      <td>https://cdn.shopify.com/s/files/1/2119/7595/pr...</td>\n",
       "      <td>0.710157</td>\n",
       "      <td>0.710157</td>\n",
       "      <td>420.0</td>\n",
       "      <td>F</td>\n",
       "      <td>76.00</td>\n",
       "      <td>The Bathpack</td>\n",
       "      <td>Bathpack</td>\n",
       "      <td>scroll</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>13</th>\n",
       "      <td>chelseaericasmith</td>\n",
       "      <td>0.2</td>\n",
       "      <td>Test Drop 10 drops w/ cogs</td>\n",
       "      <td>1</td>\n",
       "      <td>4703793545353</td>\n",
       "      <td>{\"descriptions\":[{\"icon\": \"camera\",\"text\":\"1 R...</td>\n",
       "      <td>https://cdn.shopify.com/s/files/1/2119/7595/pr...</td>\n",
       "      <td>0.710157</td>\n",
       "      <td>0.710157</td>\n",
       "      <td>420.0</td>\n",
       "      <td>F</td>\n",
       "      <td>76.00</td>\n",
       "      <td>The Bathpack</td>\n",
       "      <td>Bathpack</td>\n",
       "      <td>scroll</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>14</th>\n",
       "      <td>chelseaericasmith</td>\n",
       "      <td>1.0</td>\n",
       "      <td>Test Drop 10 drops w/ cogs</td>\n",
       "      <td>2</td>\n",
       "      <td>6583754719286</td>\n",
       "      <td>{\"descriptions\":[{\"icon\": \"camera\",\"text\":\"1 R...</td>\n",
       "      <td>https://cdn.shopify.com/s/files/1/1172/1406/pr...</td>\n",
       "      <td>0.532879</td>\n",
       "      <td>0.532879</td>\n",
       "      <td>31.0</td>\n",
       "      <td>F</td>\n",
       "      <td>695.00</td>\n",
       "      <td>LW Gold Ball Chain</td>\n",
       "      <td>Livewell Designs</td>\n",
       "      <td>scroll</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>...</th>\n",
       "      <td>...</td>\n",
       "      <td>...</td>\n",
       "      <td>...</td>\n",
       "      <td>...</td>\n",
       "      <td>...</td>\n",
       "      <td>...</td>\n",
       "      <td>...</td>\n",
       "      <td>...</td>\n",
       "      <td>...</td>\n",
       "      <td>...</td>\n",
       "      <td>...</td>\n",
       "      <td>...</td>\n",
       "      <td>...</td>\n",
       "      <td>...</td>\n",
       "      <td>...</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>2934</th>\n",
       "      <td>chelseaericasmith</td>\n",
       "      <td>1.0</td>\n",
       "      <td>Test Drop 10 drops w/ cogs</td>\n",
       "      <td>1462</td>\n",
       "      <td>4912281419878</td>\n",
       "      <td>{\"descriptions\":[{\"icon\": \"camera\",\"text\":\"1 R...</td>\n",
       "      <td>https://cdn.shopify.com/s/files/1/1944/7205/pr...</td>\n",
       "      <td>0.601788</td>\n",
       "      <td>0.601788</td>\n",
       "      <td>420.0</td>\n",
       "      <td>U</td>\n",
       "      <td>483.99</td>\n",
       "      <td>Snoop Vuitton</td>\n",
       "      <td>Canvas Cultures</td>\n",
       "      <td>scroll</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>2935</th>\n",
       "      <td>chelseaericasmith</td>\n",
       "      <td>1.0</td>\n",
       "      <td>Test Drop 10 drops w/ cogs</td>\n",
       "      <td>1463</td>\n",
       "      <td>6792410398822</td>\n",
       "      <td>{\"descriptions\":[{\"icon\": \"camera\",\"text\":\"1 R...</td>\n",
       "      <td>https://cdn.shopify.com/s/files/1/1944/7205/pr...</td>\n",
       "      <td>0.596524</td>\n",
       "      <td>0.596524</td>\n",
       "      <td>420.0</td>\n",
       "      <td>U</td>\n",
       "      <td>547.99</td>\n",
       "      <td>Lion</td>\n",
       "      <td>Canvas Cultures</td>\n",
       "      <td>scroll</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>2936</th>\n",
       "      <td>chelseaericasmith</td>\n",
       "      <td>0.2</td>\n",
       "      <td>Test Drop 10 drops w/ cogs</td>\n",
       "      <td>1463</td>\n",
       "      <td>6792410398822</td>\n",
       "      <td>{\"descriptions\":[{\"icon\": \"camera\",\"text\":\"1 R...</td>\n",
       "      <td>https://cdn.shopify.com/s/files/1/1944/7205/pr...</td>\n",
       "      <td>0.596524</td>\n",
       "      <td>0.596524</td>\n",
       "      <td>420.0</td>\n",
       "      <td>U</td>\n",
       "      <td>547.99</td>\n",
       "      <td>Lion</td>\n",
       "      <td>Canvas Cultures</td>\n",
       "      <td>scroll</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>2937</th>\n",
       "      <td>chelseaericasmith</td>\n",
       "      <td>0.2</td>\n",
       "      <td>Test Drop 10 drops w/ cogs</td>\n",
       "      <td>1464</td>\n",
       "      <td>6792397520998</td>\n",
       "      <td>{\"descriptions\":[{\"icon\": \"camera\",\"text\":\"1 R...</td>\n",
       "      <td>https://cdn.shopify.com/s/files/1/1944/7205/pr...</td>\n",
       "      <td>0.602695</td>\n",
       "      <td>0.602695</td>\n",
       "      <td>420.0</td>\n",
       "      <td>U</td>\n",
       "      <td>949.99</td>\n",
       "      <td>AP Skeleton Rose</td>\n",
       "      <td>Canvas Cultures</td>\n",
       "      <td>scroll</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>2938</th>\n",
       "      <td>chelseaericasmith</td>\n",
       "      <td>1.0</td>\n",
       "      <td>Test Drop 10 drops w/ cogs</td>\n",
       "      <td>1464</td>\n",
       "      <td>6792397520998</td>\n",
       "      <td>{\"descriptions\":[{\"icon\": \"camera\",\"text\":\"1 R...</td>\n",
       "      <td>https://cdn.shopify.com/s/files/1/1944/7205/pr...</td>\n",
       "      <td>0.602695</td>\n",
       "      <td>0.602695</td>\n",
       "      <td>420.0</td>\n",
       "      <td>U</td>\n",
       "      <td>949.99</td>\n",
       "      <td>AP Skeleton Rose</td>\n",
       "      <td>Canvas Cultures</td>\n",
       "      <td>scroll</td>\n",
       "    </tr>\n",
       "  </tbody>\n",
       "</table>\n",
       "<p>2929 rows × 15 columns</p>\n",
       "</div>"
      ],
      "text/plain": [
       "             CREATOR_ID  DISCOUNT_PERCENTAGE                  ASSIGNMENT  \\\n",
       "10    chelseaericasmith                  0.2  Test Drop 10 drops w/ cogs   \n",
       "11    chelseaericasmith                  1.0  Test Drop 10 drops w/ cogs   \n",
       "12    chelseaericasmith                  1.0  Test Drop 10 drops w/ cogs   \n",
       "13    chelseaericasmith                  0.2  Test Drop 10 drops w/ cogs   \n",
       "14    chelseaericasmith                  1.0  Test Drop 10 drops w/ cogs   \n",
       "...                 ...                  ...                         ...   \n",
       "2934  chelseaericasmith                  1.0  Test Drop 10 drops w/ cogs   \n",
       "2935  chelseaericasmith                  1.0  Test Drop 10 drops w/ cogs   \n",
       "2936  chelseaericasmith                  0.2  Test Drop 10 drops w/ cogs   \n",
       "2937  chelseaericasmith                  0.2  Test Drop 10 drops w/ cogs   \n",
       "2938  chelseaericasmith                  1.0  Test Drop 10 drops w/ cogs   \n",
       "\n",
       "      SORT_ORDER     PRODUCT_ID  \\\n",
       "10             0      114589574   \n",
       "11             0      114589574   \n",
       "12             1  4703793545353   \n",
       "13             1  4703793545353   \n",
       "14             2  6583754719286   \n",
       "...          ...            ...   \n",
       "2934        1462  4912281419878   \n",
       "2935        1463  6792410398822   \n",
       "2936        1463  6792410398822   \n",
       "2937        1464  6792397520998   \n",
       "2938        1464  6792397520998   \n",
       "\n",
       "                                        COLLAB_METADATA  \\\n",
       "10                                                 None   \n",
       "11                                                 None   \n",
       "12    {\"descriptions\":[{\"icon\": \"camera\",\"text\":\"1 R...   \n",
       "13    {\"descriptions\":[{\"icon\": \"camera\",\"text\":\"1 R...   \n",
       "14    {\"descriptions\":[{\"icon\": \"camera\",\"text\":\"1 R...   \n",
       "...                                                 ...   \n",
       "2934  {\"descriptions\":[{\"icon\": \"camera\",\"text\":\"1 R...   \n",
       "2935  {\"descriptions\":[{\"icon\": \"camera\",\"text\":\"1 R...   \n",
       "2936  {\"descriptions\":[{\"icon\": \"camera\",\"text\":\"1 R...   \n",
       "2937  {\"descriptions\":[{\"icon\": \"camera\",\"text\":\"1 R...   \n",
       "2938  {\"descriptions\":[{\"icon\": \"camera\",\"text\":\"1 R...   \n",
       "\n",
       "                                               IMAGEURL  PRODUCT_GROSS_MARGIN  \\\n",
       "10    https://cdn.shopify.com/s/files/1/0200/5278/pr...              0.271190   \n",
       "11    https://cdn.shopify.com/s/files/1/0200/5278/pr...              0.271190   \n",
       "12    https://cdn.shopify.com/s/files/1/2119/7595/pr...              0.710157   \n",
       "13    https://cdn.shopify.com/s/files/1/2119/7595/pr...              0.710157   \n",
       "14    https://cdn.shopify.com/s/files/1/1172/1406/pr...              0.532879   \n",
       "...                                                 ...                   ...   \n",
       "2934  https://cdn.shopify.com/s/files/1/1944/7205/pr...              0.601788   \n",
       "2935  https://cdn.shopify.com/s/files/1/1944/7205/pr...              0.596524   \n",
       "2936  https://cdn.shopify.com/s/files/1/1944/7205/pr...              0.596524   \n",
       "2937  https://cdn.shopify.com/s/files/1/1944/7205/pr...              0.602695   \n",
       "2938  https://cdn.shopify.com/s/files/1/1944/7205/pr...              0.602695   \n",
       "\n",
       "      BREAKEVEN_DISCOUNT_PCT  MAX_CLAIMED_COUNT GENDER_CLEANED    PRICE  \\\n",
       "10                  0.271190              420.0              U  1599.99   \n",
       "11                  0.271190              420.0              U  1599.99   \n",
       "12                  0.710157              420.0              F    76.00   \n",
       "13                  0.710157              420.0              F    76.00   \n",
       "14                  0.532879               31.0              F   695.00   \n",
       "...                      ...                ...            ...      ...   \n",
       "2934                0.601788              420.0              U   483.99   \n",
       "2935                0.596524              420.0              U   547.99   \n",
       "2936                0.596524              420.0              U   547.99   \n",
       "2937                0.602695              420.0              U   949.99   \n",
       "2938                0.602695              420.0              U   949.99   \n",
       "\n",
       "                   PRODUCT_TITLE       OS_MERCHANT  STATUS  \n",
       "10    10\" Organic Latex Mattress  Spindle Mattress  scroll  \n",
       "11    10\" Organic Latex Mattress  Spindle Mattress  scroll  \n",
       "12                  The Bathpack          Bathpack  scroll  \n",
       "13                  The Bathpack          Bathpack  scroll  \n",
       "14            LW Gold Ball Chain  Livewell Designs  scroll  \n",
       "...                          ...               ...     ...  \n",
       "2934               Snoop Vuitton   Canvas Cultures  scroll  \n",
       "2935                        Lion   Canvas Cultures  scroll  \n",
       "2936                        Lion   Canvas Cultures  scroll  \n",
       "2937            AP Skeleton Rose   Canvas Cultures  scroll  \n",
       "2938            AP Skeleton Rose   Canvas Cultures  scroll  \n",
       "\n",
       "[2929 rows x 15 columns]"
      ]
     },
     "execution_count": 21,
     "metadata": {},
     "output_type": "execute_result"
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "2022-12-03 10:30:19.706 WARNING snowflake.connector.vendored.urllib3.connectionpool: Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<snowflake.connector.vendored.urllib3.connection.HTTPSConnection object at 0x7fc7d184ba00>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known')': /session/heartbeat?requestId=ccbea51b-3929-4d78-b6da-cc2fe9eae41e&request_guid=42b97de4-ade0-4f3c-bd2c-3079a42281e3\n",
      "2022-12-03 10:30:20.798 WARNING snowflake.connector.vendored.urllib3.connectionpool: Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<snowflake.connector.vendored.urllib3.connection.HTTPSConnection object at 0x7fc7d177dd30>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known')': /session/heartbeat?requestId=ccbea51b-3929-4d78-b6da-cc2fe9eae41e&request_guid=b7d2d87f-2059-49cf-8ec0-61f9895479e7\n",
      "2022-12-03 10:30:21.818 WARNING snowflake.connector.vendored.urllib3.connectionpool: Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<snowflake.connector.vendored.urllib3.connection.HTTPSConnection object at 0x7fc7d184bdc0>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known')': /session/heartbeat?requestId=ccbea51b-3929-4d78-b6da-cc2fe9eae41e&request_guid=9f573592-b623-45b3-b3e0-f9eca70ce3b9\n",
      "2022-12-03 10:30:23.834 WARNING snowflake.connector.vendored.urllib3.connectionpool: Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<snowflake.connector.vendored.urllib3.connection.HTTPSConnection object at 0x7fc7c1163280>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known')': /session/heartbeat?requestId=ccbea51b-3929-4d78-b6da-cc2fe9eae41e&request_guid=865159b7-32b3-4e2a-bc94-d36110953cf0\n",
      "2022-12-03 10:30:25.864 WARNING snowflake.connector.vendored.urllib3.connectionpool: Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<snowflake.connector.vendored.urllib3.connection.HTTPSConnection object at 0x7fc7b3ae68b0>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known')': /session/heartbeat?requestId=ccbea51b-3929-4d78-b6da-cc2fe9eae41e&request_guid=920d5f64-0476-470f-8f96-91b2ce4393f0\n",
      "2022-12-03 10:30:29.885 WARNING snowflake.connector.vendored.urllib3.connectionpool: Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<snowflake.connector.vendored.urllib3.connection.HTTPSConnection object at 0x7fc7b3007b20>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known')': /session/heartbeat?requestId=ccbea51b-3929-4d78-b6da-cc2fe9eae41e&request_guid=02d43483-5a37-4b83-97b4-81d7ea729ac7\n",
      "2022-12-03 10:30:37.927 WARNING snowflake.connector.vendored.urllib3.connectionpool: Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<snowflake.connector.vendored.urllib3.connection.HTTPSConnection object at 0x7fc7b3b62940>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known')': /session/heartbeat?requestId=ccbea51b-3929-4d78-b6da-cc2fe9eae41e&request_guid=f69a6b41-9869-47a0-a240-706159ca981e\n",
      "2022-12-03 10:48:16.830 WARNING snowflake.connector.vendored.urllib3.connectionpool: Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<snowflake.connector.vendored.urllib3.connection.HTTPSConnection object at 0x7fc7d177da60>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known')': /session/heartbeat?requestId=ccbea51b-3929-4d78-b6da-cc2fe9eae41e&request_guid=4ff21e5a-4382-4358-bb62-7f504254ac25\n",
      "2022-12-03 11:05:08.598 WARNING snowflake.connector.vendored.urllib3.connectionpool: Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<snowflake.connector.vendored.urllib3.connection.HTTPSConnection object at 0x7fc7d184b460>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known')': /session/token-request?requestId=6e698102-f1ec-40e6-affe-3736a955f459&request_guid=455bb906-9a3e-4ddb-8e5b-ba1e00bb747d\n",
      "2022-12-03 11:05:09.627 WARNING snowflake.connector.vendored.urllib3.connectionpool: Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<snowflake.connector.vendored.urllib3.connection.HTTPSConnection object at 0x7fc7b31eab50>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known')': /session/token-request?requestId=6e698102-f1ec-40e6-affe-3736a955f459&request_guid=cbfb002f-6f28-41eb-9f37-079fe5cbb474\n",
      "2022-12-03 11:05:12.648 WARNING snowflake.connector.vendored.urllib3.connectionpool: Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<snowflake.connector.vendored.urllib3.connection.HTTPSConnection object at 0x7fc7b31ea820>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known')': /session/token-request?requestId=6e698102-f1ec-40e6-affe-3736a955f459&request_guid=cd24bd6e-869c-41a6-8a4a-926c97310604\n",
      "2022-12-03 11:21:20.706 WARNING snowflake.connector.vendored.urllib3.connectionpool: Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<snowflake.connector.vendored.urllib3.connection.HTTPSConnection object at 0x7fc7b2dd4070>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known')': /session/token-request?requestId=6e698102-f1ec-40e6-affe-3736a955f459&request_guid=3c68ca14-a6b5-434d-b16f-746bfc70b76c\n",
      "2022-12-03 11:21:23.730 WARNING snowflake.connector.vendored.urllib3.connectionpool: Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<snowflake.connector.vendored.urllib3.connection.HTTPSConnection object at 0x7fc7b2dd4190>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known')': /session/token-request?requestId=6e698102-f1ec-40e6-affe-3736a955f459&request_guid=e3104848-e44c-4867-b83b-30dd493753cc\n",
      "2022-12-03 11:38:10.591 WARNING snowflake.connector.vendored.urllib3.connectionpool: Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<snowflake.connector.vendored.urllib3.connection.HTTPSConnection object at 0x7fc7a10fa880>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known')': /session/token-request?requestId=6e698102-f1ec-40e6-affe-3736a955f459&request_guid=8fc9590f-b125-4002-a7fe-55f3bf21ebcc\n",
      "2022-12-03 11:55:04.808 WARNING snowflake.connector.vendored.urllib3.connectionpool: Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<snowflake.connector.vendored.urllib3.connection.HTTPSConnection object at 0x7fc7b31ea820>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known')': /session/token-request?requestId=6e698102-f1ec-40e6-affe-3736a955f459&request_guid=fdf3d21a-93db-488e-aa60-3262a179805c\n",
      "2022-12-03 12:00:15.502 WARNING snowflake.connector.vendored.urllib3.connectionpool: Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<snowflake.connector.vendored.urllib3.connection.HTTPSConnection object at 0x7fc7b31ea6d0>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known')': /session/token-request?requestId=6e698102-f1ec-40e6-affe-3736a955f459&request_guid=2a6035fb-63bf-436d-b5b1-e978f990f012\n",
      "2022-12-03 12:00:24.661 WARNING snowflake.connector.vendored.urllib3.connectionpool: Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<snowflake.connector.vendored.urllib3.connection.HTTPSConnection object at 0x7fc7b2dd43d0>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known')': /session/token-request?requestId=6e698102-f1ec-40e6-affe-3736a955f459&request_guid=e2f0e7f4-b049-43b6-a69c-e90dd52680ef\n",
      "2022-12-03 12:00:40.774 WARNING snowflake.connector.vendored.urllib3.connectionpool: Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<snowflake.connector.vendored.urllib3.connection.HTTPSConnection object at 0x7fc7b2dd4e20>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known')': /session/token-request?requestId=6e698102-f1ec-40e6-affe-3736a955f459&request_guid=f8a8efae-2f3e-4d40-bad5-7d5fd0963ebe\n",
      "2022-12-03 12:09:39.354 WARNING snowflake.connector.vendored.urllib3.connectionpool: Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<snowflake.connector.vendored.urllib3.connection.HTTPSConnection object at 0x7fc7d184bf70>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known')': /session/token-request?requestId=6e698102-f1ec-40e6-affe-3736a955f459&request_guid=985bc605-a296-4199-9282-e88445af1d96\n",
      "2022-12-03 12:09:48.379 WARNING snowflake.connector.vendored.urllib3.connectionpool: Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<snowflake.connector.vendored.urllib3.connection.HTTPSConnection object at 0x7fc7d184b0d0>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known')': /session/token-request?requestId=6e698102-f1ec-40e6-affe-3736a955f459&request_guid=0056007b-5148-4031-b6b2-24d97e2bb837\n",
      "2022-12-03 12:27:33.471 WARNING snowflake.connector.vendored.urllib3.connectionpool: Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<snowflake.connector.vendored.urllib3.connection.HTTPSConnection object at 0x7fc7a14dcc70>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known')': /session/token-request?requestId=6e698102-f1ec-40e6-affe-3736a955f459&request_guid=8949df17-8167-45a4-ab4e-3bea58827122\n",
      "2022-12-03 12:58:17.740 WARNING snowflake.connector.vendored.urllib3.connectionpool: Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<snowflake.connector.vendored.urllib3.connection.HTTPSConnection object at 0x7fc7d184bd60>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known')': /session/token-request?requestId=6e698102-f1ec-40e6-affe-3736a955f459&request_guid=8cf0bc63-3dc7-4d2c-8bdd-a8d3496210a6\n",
      "2022-12-03 13:13:36.806 WARNING snowflake.connector.vendored.urllib3.connectionpool: Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<snowflake.connector.vendored.urllib3.connection.HTTPSConnection object at 0x7fc7d184bdf0>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known')': /session/token-request?requestId=6e698102-f1ec-40e6-affe-3736a955f459&request_guid=093b8e07-8d34-4e2d-b83f-36868d22d238\n",
      "2022-12-03 13:47:18.530 WARNING snowflake.connector.vendored.urllib3.connectionpool: Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<snowflake.connector.vendored.urllib3.connection.HTTPSConnection object at 0x7fc7b2dd44c0>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known')': /session/token-request?requestId=6e698102-f1ec-40e6-affe-3736a955f459&request_guid=36024e78-51a5-4c91-9c38-26b1d45d32c4\n",
      "2022-12-03 14:19:47.495 WARNING snowflake.connector.vendored.urllib3.connectionpool: Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<snowflake.connector.vendored.urllib3.connection.HTTPSConnection object at 0x7fc7b2dd4730>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known')': /session/token-request?requestId=6e698102-f1ec-40e6-affe-3736a955f459&request_guid=5260764f-cdda-47cb-9e92-70142fa02ed0\n",
      "2022-12-03 14:52:54.293 WARNING snowflake.connector.vendored.urllib3.connectionpool: Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<snowflake.connector.vendored.urllib3.connection.HTTPSConnection object at 0x7fc7b31eae80>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known')': /session/token-request?requestId=6e698102-f1ec-40e6-affe-3736a955f459&request_guid=4f1d2ae9-0026-4f8d-acb7-625d5aff21a3\n",
      "2022-12-03 15:26:50.637 WARNING snowflake.connector.vendored.urllib3.connectionpool: Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<snowflake.connector.vendored.urllib3.connection.HTTPSConnection object at 0x7fc7b31ea760>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known')': /session/token-request?requestId=6e698102-f1ec-40e6-affe-3736a955f459&request_guid=f6c83bc2-36ef-475c-9542-622d6fe35044\n",
      "2022-12-03 15:59:11.725 WARNING snowflake.connector.vendored.urllib3.connectionpool: Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<snowflake.connector.vendored.urllib3.connection.HTTPSConnection object at 0x7fc7d177d520>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known')': /session/token-request?requestId=6e698102-f1ec-40e6-affe-3736a955f459&request_guid=c582f92c-9ba9-4213-b26a-eb9b64cdf32b\n",
      "2022-12-03 16:15:05.241 WARNING snowflake.connector.vendored.urllib3.connectionpool: Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<snowflake.connector.vendored.urllib3.connection.HTTPSConnection object at 0x7fc7b31eaaf0>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known')': /session/token-request?requestId=6e698102-f1ec-40e6-affe-3736a955f459&request_guid=e89cf1a5-a53a-4256-963b-b6206aa591d7\n",
      "2022-12-03 16:48:06.616 WARNING snowflake.connector.vendored.urllib3.connectionpool: Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<snowflake.connector.vendored.urllib3.connection.HTTPSConnection object at 0x7fc7b31ea9a0>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known')': /session/token-request?requestId=6e698102-f1ec-40e6-affe-3736a955f459&request_guid=67b7059f-03a3-455d-9750-c1dbc2453675\n",
      "2022-12-03 17:04:45.928 WARNING snowflake.connector.vendored.urllib3.connectionpool: Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<snowflake.connector.vendored.urllib3.connection.HTTPSConnection object at 0x7fc7b2dd4820>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known')': /session/token-request?requestId=6e698102-f1ec-40e6-affe-3736a955f459&request_guid=9b8d6036-19c0-4b23-b8d5-1a1c53578d61\n",
      "2022-12-03 17:20:50.344 WARNING snowflake.connector.vendored.urllib3.connectionpool: Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<snowflake.connector.vendored.urllib3.connection.HTTPSConnection object at 0x7fc7b2dd4fd0>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known')': /session/token-request?requestId=6e698102-f1ec-40e6-affe-3736a955f459&request_guid=9d8d02f1-6e4d-47b4-9dde-9aff7903ec0f\n",
      "2022-12-03 17:20:56.375 WARNING snowflake.connector.vendored.urllib3.connectionpool: Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<snowflake.connector.vendored.urllib3.connection.HTTPSConnection object at 0x7fc7d184b7c0>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known')': /session/token-request?requestId=6e698102-f1ec-40e6-affe-3736a955f459&request_guid=d38fdc10-101d-4096-b52a-3309e0e7c180\n",
      "2022-12-03 17:37:04.334 WARNING snowflake.connector.vendored.urllib3.connectionpool: Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<snowflake.connector.vendored.urllib3.connection.HTTPSConnection object at 0x7fc7d184bf10>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known')': /session/token-request?requestId=6e698102-f1ec-40e6-affe-3736a955f459&request_guid=0ac3023e-aa0a-4172-a65a-f90a1316ee00\n",
      "2022-12-03 17:37:05.357 WARNING snowflake.connector.vendored.urllib3.connectionpool: Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<snowflake.connector.vendored.urllib3.connection.HTTPSConnection object at 0x7fc7b30078e0>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known')': /session/token-request?requestId=6e698102-f1ec-40e6-affe-3736a955f459&request_guid=e7975383-25bd-41bb-87e0-2bdfd92c7907\n",
      "2022-12-03 17:37:08.381 WARNING snowflake.connector.vendored.urllib3.connectionpool: Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<snowflake.connector.vendored.urllib3.connection.HTTPSConnection object at 0x7fc7b3007d60>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known')': /session/token-request?requestId=6e698102-f1ec-40e6-affe-3736a955f459&request_guid=ecb1ebd9-17ce-42c5-8aa4-55159786deb3\n",
      "2022-12-03 17:52:58.111 WARNING snowflake.connector.vendored.urllib3.connectionpool: Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<snowflake.connector.vendored.urllib3.connection.HTTPSConnection object at 0x7fc7d184b670>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known')': /session/token-request?requestId=6e698102-f1ec-40e6-affe-3736a955f459&request_guid=7d4dc770-f34c-47b4-a81d-dc246e95e4b2\n",
      "2022-12-03 17:58:14.730 WARNING snowflake.connector.vendored.urllib3.connectionpool: Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<snowflake.connector.vendored.urllib3.connection.HTTPSConnection object at 0x7fc7d184b040>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known')': /session/token-request?requestId=6e698102-f1ec-40e6-affe-3736a955f459&request_guid=db8cd079-4bf0-40a4-a8ef-a7d37e435876\n",
      "2022-12-11 16:00:25.564 WARNING snowflake.connector.vendored.urllib3.connectionpool: Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<snowflake.connector.vendored.urllib3.connection.HTTPSConnection object at 0x7fc7a10fac70>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known')': /session/heartbeat?requestId=a9e225d3-9710-4e5e-8942-0ad9a24cba3c&request_guid=03260e7f-1767-4490-8ba4-85930ca6df20\n",
      "2022-12-11 16:18:11.633 WARNING snowflake.connector.vendored.urllib3.connectionpool: Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<snowflake.connector.vendored.urllib3.connection.HTTPSConnection object at 0x7fc7a14e5910>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known')': /session/heartbeat?requestId=a9e225d3-9710-4e5e-8942-0ad9a24cba3c&request_guid=9b9ce7d6-2eb1-4c96-a8d3-c50aa90f8429\n",
      "2022-12-11 16:18:15.660 WARNING snowflake.connector.vendored.urllib3.connectionpool: Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<snowflake.connector.vendored.urllib3.connection.HTTPSConnection object at 0x7fc7b3199f40>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known')': /session/heartbeat?requestId=a9e225d3-9710-4e5e-8942-0ad9a24cba3c&request_guid=1450f023-4b9b-432d-9241-4d10b6638acc\n",
      "2022-12-11 16:18:20.683 WARNING snowflake.connector.vendored.urllib3.connectionpool: Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<snowflake.connector.vendored.urllib3.connection.HTTPSConnection object at 0x7fc7b31c0fd0>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known')': /session/heartbeat?requestId=a9e225d3-9710-4e5e-8942-0ad9a24cba3c&request_guid=ec559481-fe7a-44b3-b95a-e9d276ac87f2\n",
      "2022-12-11 16:27:48.921 WARNING snowflake.connector.vendored.urllib3.connectionpool: Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<snowflake.connector.vendored.urllib3.connection.HTTPSConnection object at 0x7fc7b3085c40>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known')': /session/heartbeat?requestId=a9e225d3-9710-4e5e-8942-0ad9a24cba3c&request_guid=b7173751-99c5-48ad-8458-720e2bb7476c\n",
      "2022-12-11 16:28:04.953 WARNING snowflake.connector.vendored.urllib3.connectionpool: Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<snowflake.connector.vendored.urllib3.connection.HTTPSConnection object at 0x7fc7b2d99fd0>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known')': /session/heartbeat?requestId=a9e225d3-9710-4e5e-8942-0ad9a24cba3c&request_guid=30cfbc5a-0c72-465c-8cd1-75c51ce2d7c2\n",
      "2022-12-11 16:44:59.668 WARNING snowflake.connector.vendored.urllib3.connectionpool: Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<snowflake.connector.vendored.urllib3.connection.HTTPSConnection object at 0x7fc7b2d993a0>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known')': /session/heartbeat?requestId=a9e225d3-9710-4e5e-8942-0ad9a24cba3c&request_guid=cb5a5425-38d1-486e-821a-1b6ead644671\n",
      "2022-12-11 17:16:06.203 WARNING snowflake.connector.vendored.urllib3.connectionpool: Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<snowflake.connector.vendored.urllib3.connection.HTTPSConnection object at 0x7fc7b3199d00>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known')': /session/heartbeat?requestId=a9e225d3-9710-4e5e-8942-0ad9a24cba3c&request_guid=e9d20c98-c149-4375-a33d-dd67e9845e9a\n",
      "2022-12-11 17:16:11.218 WARNING snowflake.connector.vendored.urllib3.connectionpool: Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<snowflake.connector.vendored.urllib3.connection.HTTPSConnection object at 0x7fc7b31eab50>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known')': /session/heartbeat?requestId=a9e225d3-9710-4e5e-8942-0ad9a24cba3c&request_guid=362a7011-8569-4a44-8833-445d3ffe1693\n",
      "2022-12-11 17:16:13.233 WARNING snowflake.connector.vendored.urllib3.connectionpool: Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<snowflake.connector.vendored.urllib3.connection.HTTPSConnection object at 0x7fc7a14e5400>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known')': /session/heartbeat?requestId=a9e225d3-9710-4e5e-8942-0ad9a24cba3c&request_guid=8168ee86-ce22-4b0c-8b7e-16f1ada57fe8\n",
      "2022-12-11 17:16:15.252 WARNING snowflake.connector.vendored.urllib3.connectionpool: Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<snowflake.connector.vendored.urllib3.connection.HTTPSConnection object at 0x7fc7a14e5340>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known')': /session/heartbeat?requestId=a9e225d3-9710-4e5e-8942-0ad9a24cba3c&request_guid=950ca04a-0083-40f0-b495-1d79d538754f\n",
      "2022-12-11 17:31:13.312 WARNING snowflake.connector.vendored.urllib3.connectionpool: Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<snowflake.connector.vendored.urllib3.connection.HTTPSConnection object at 0x7fc7b3085a60>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known')': /session/heartbeat?requestId=a9e225d3-9710-4e5e-8942-0ad9a24cba3c&request_guid=50fd5406-5ccf-4811-8e66-d646a08f47d8\n",
      "2022-12-11 17:46:44.866 WARNING snowflake.connector.vendored.urllib3.connectionpool: Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<snowflake.connector.vendored.urllib3.connection.HTTPSConnection object at 0x7fc7b31c0c10>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known')': /session/heartbeat?requestId=a9e225d3-9710-4e5e-8942-0ad9a24cba3c&request_guid=c255e821-7371-4f83-aafa-676f7cf93bfc\n",
      "2022-12-11 18:18:32.845 WARNING snowflake.connector.vendored.urllib3.connectionpool: Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<snowflake.connector.vendored.urllib3.connection.HTTPSConnection object at 0x7fc7b2d99640>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known')': /session/heartbeat?requestId=a9e225d3-9710-4e5e-8942-0ad9a24cba3c&request_guid=f755d45f-cf45-417a-845c-7742a40f179f\n",
      "2022-12-11 18:36:37.856 WARNING snowflake.connector.vendored.urllib3.connectionpool: Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<snowflake.connector.vendored.urllib3.connection.HTTPSConnection object at 0x7fc7b31c0cd0>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known')': /session/heartbeat?requestId=a9e225d3-9710-4e5e-8942-0ad9a24cba3c&request_guid=4c034f65-3274-4bff-8572-632fb3539325\n",
      "2022-12-11 18:36:53.877 WARNING snowflake.connector.vendored.urllib3.connectionpool: Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<snowflake.connector.vendored.urllib3.connection.HTTPSConnection object at 0x7fc7b300ecd0>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known')': /session/heartbeat?requestId=a9e225d3-9710-4e5e-8942-0ad9a24cba3c&request_guid=8fa4bbfa-41c5-486a-88b8-c733081e3d87\n",
      "2022-12-11 18:37:09.894 WARNING snowflake.connector.vendored.urllib3.connectionpool: Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<snowflake.connector.vendored.urllib3.connection.HTTPSConnection object at 0x7fc7a14e52b0>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known')': /session/heartbeat?requestId=a9e225d3-9710-4e5e-8942-0ad9a24cba3c&request_guid=9faa2442-ef2c-4d3c-aae3-fcd2cfb5ab57\n",
      "2022-12-11 18:37:25.910 WARNING snowflake.connector.vendored.urllib3.connectionpool: Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<snowflake.connector.vendored.urllib3.connection.HTTPSConnection object at 0x7fc7a14e5df0>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known')': /session/heartbeat?requestId=a9e225d3-9710-4e5e-8942-0ad9a24cba3c&request_guid=b805ad1e-3fa8-4ae2-b538-a639c1c0b88d\n",
      "2022-12-11 18:54:19.208 WARNING snowflake.connector.vendored.urllib3.connectionpool: Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<snowflake.connector.vendored.urllib3.connection.HTTPSConnection object at 0x7fc7b31ea790>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known')': /session/heartbeat?requestId=a9e225d3-9710-4e5e-8942-0ad9a24cba3c&request_guid=9f56e926-8b52-4472-9782-60b91af7000a\n",
      "2022-12-11 19:10:35.864 WARNING snowflake.connector.vendored.urllib3.connectionpool: Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<snowflake.connector.vendored.urllib3.connection.HTTPSConnection object at 0x7fc7b3199160>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known')': /session/heartbeat?requestId=a9e225d3-9710-4e5e-8942-0ad9a24cba3c&request_guid=4e0fe6fd-789b-426b-acef-89f61a88ed40\n",
      "2022-12-11 19:10:51.890 WARNING snowflake.connector.vendored.urllib3.connectionpool: Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<snowflake.connector.vendored.urllib3.connection.HTTPSConnection object at 0x7fc7a14d00d0>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known')': /session/heartbeat?requestId=a9e225d3-9710-4e5e-8942-0ad9a24cba3c&request_guid=9cda53dc-06f9-4920-8dc6-7ede6218ae2c\n",
      "2022-12-11 19:11:07.905 WARNING snowflake.connector.vendored.urllib3.connectionpool: Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<snowflake.connector.vendored.urllib3.connection.HTTPSConnection object at 0x7fc7b3199220>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known')': /session/heartbeat?requestId=a9e225d3-9710-4e5e-8942-0ad9a24cba3c&request_guid=e0488c41-8181-4648-84c2-c72e00a37507\n",
      "2022-12-11 19:11:23.928 WARNING snowflake.connector.vendored.urllib3.connectionpool: Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<snowflake.connector.vendored.urllib3.connection.HTTPSConnection object at 0x7fc7b2dddb80>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known')': /session/heartbeat?requestId=a9e225d3-9710-4e5e-8942-0ad9a24cba3c&request_guid=f5cdac5c-b4d9-484d-9a3f-adacdb37439c\n",
      "2022-12-11 19:27:03.043 WARNING snowflake.connector.vendored.urllib3.connectionpool: Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<snowflake.connector.vendored.urllib3.connection.HTTPSConnection object at 0x7fc7a14e57f0>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known')': /session/heartbeat?requestId=a9e225d3-9710-4e5e-8942-0ad9a24cba3c&request_guid=2ac062c5-8928-48d7-b063-d4a0d1ba1872\n",
      "2022-12-11 19:54:22.703 WARNING snowflake.connector.vendored.urllib3.connectionpool: Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<snowflake.connector.vendored.urllib3.connection.HTTPSConnection object at 0x7fc7a14e57c0>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known')': /session/heartbeat?requestId=a9e225d3-9710-4e5e-8942-0ad9a24cba3c&request_guid=0e85a4b8-7ad1-4d47-aae4-a62148326c05\n",
      "2022-12-11 19:54:38.721 WARNING snowflake.connector.vendored.urllib3.connectionpool: Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<snowflake.connector.vendored.urllib3.connection.HTTPSConnection object at 0x7fc7b3ae6190>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known')': /session/heartbeat?requestId=a9e225d3-9710-4e5e-8942-0ad9a24cba3c&request_guid=323777fc-58fa-4030-921b-1bdd539f48b8\n",
      "2022-12-11 19:54:42.746 WARNING snowflake.connector.vendored.urllib3.connectionpool: Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<snowflake.connector.vendored.urllib3.connection.HTTPSConnection object at 0x7fc7b31c0c70>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known')': /session/heartbeat?requestId=a9e225d3-9710-4e5e-8942-0ad9a24cba3c&request_guid=3696b013-d6ae-484d-95fb-6246bad7b5be\n",
      "2022-12-11 19:54:53.759 WARNING snowflake.connector.vendored.urllib3.connectionpool: Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<snowflake.connector.vendored.urllib3.connection.HTTPSConnection object at 0x7fc7b3e07490>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known')': /session/heartbeat?requestId=a9e225d3-9710-4e5e-8942-0ad9a24cba3c&request_guid=e872ab8e-d36e-4f13-95eb-f0cff3ef2306\n",
      "2022-12-11 20:25:45.764 WARNING snowflake.connector.vendored.urllib3.connectionpool: Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<snowflake.connector.vendored.urllib3.connection.HTTPSConnection object at 0x7fc7b31c0d90>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known')': /session/heartbeat?requestId=a9e225d3-9710-4e5e-8942-0ad9a24cba3c&request_guid=aa0ff121-d895-4fb5-9f29-e2e923e67010\n",
      "2022-12-11 20:42:23.651 WARNING snowflake.connector.vendored.urllib3.connectionpool: Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<snowflake.connector.vendored.urllib3.connection.HTTPSConnection object at 0x7fc7b3085a60>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known')': /session/heartbeat?requestId=a9e225d3-9710-4e5e-8942-0ad9a24cba3c&request_guid=a9252af0-8013-49e1-9ff8-90e99f001d35\n",
      "2022-12-11 21:16:57.684 WARNING snowflake.connector.vendored.urllib3.connectionpool: Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<snowflake.connector.vendored.urllib3.connection.HTTPSConnection object at 0x7fc7a14e5dc0>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known')': /session/heartbeat?requestId=a9e225d3-9710-4e5e-8942-0ad9a24cba3c&request_guid=1295900e-e5d5-4ba4-b9e4-79f829df1ebf\n",
      "2022-12-11 21:34:09.775 WARNING snowflake.connector.vendored.urllib3.connectionpool: Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<snowflake.connector.vendored.urllib3.connection.HTTPSConnection object at 0x7fc7a14e5e80>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known')': /session/heartbeat?requestId=a9e225d3-9710-4e5e-8942-0ad9a24cba3c&request_guid=0e18b91b-1823-4c00-97cb-c7651160c9de\n",
      "2022-12-11 22:07:37.885 WARNING snowflake.connector.vendored.urllib3.connectionpool: Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<snowflake.connector.vendored.urllib3.connection.HTTPSConnection object at 0x7fc7b31ea490>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known')': /session/heartbeat?requestId=a9e225d3-9710-4e5e-8942-0ad9a24cba3c&request_guid=39568f86-43e6-4fef-b961-a6922a115153\n",
      "2022-12-11 22:23:53.894 WARNING snowflake.connector.vendored.urllib3.connectionpool: Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<snowflake.connector.vendored.urllib3.connection.HTTPSConnection object at 0x7fc7b3e2b520>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known')': /session/heartbeat?requestId=a9e225d3-9710-4e5e-8942-0ad9a24cba3c&request_guid=26ab88a4-6910-4bd9-a1f5-ed96aac92800\n",
      "2022-12-11 22:41:38.594 WARNING snowflake.connector.vendored.urllib3.connectionpool: Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<snowflake.connector.vendored.urllib3.connection.HTTPSConnection object at 0x7fc7b3e07c70>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known')': /session/heartbeat?requestId=a9e225d3-9710-4e5e-8942-0ad9a24cba3c&request_guid=fe82c831-bd41-4cd7-92cb-e52fae447920\n",
      "2022-12-11 23:13:44.140 WARNING snowflake.connector.vendored.urllib3.connectionpool: Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<snowflake.connector.vendored.urllib3.connection.HTTPSConnection object at 0x7fc7a14d0d90>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known')': /session/heartbeat?requestId=a9e225d3-9710-4e5e-8942-0ad9a24cba3c&request_guid=ba77f237-2ea7-46bd-b6dc-a26167b21339\n",
      "2022-12-11 23:29:49.131 WARNING snowflake.connector.vendored.urllib3.connectionpool: Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<snowflake.connector.vendored.urllib3.connection.HTTPSConnection object at 0x7fc7b2ddd310>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known')': /session/heartbeat?requestId=a9e225d3-9710-4e5e-8942-0ad9a24cba3c&request_guid=b677a79a-c80d-4c0b-b4be-cdf5e5120a1c\n",
      "2022-12-11 23:45:57.095 WARNING snowflake.connector.vendored.urllib3.connectionpool: Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<snowflake.connector.vendored.urllib3.connection.HTTPSConnection object at 0x7fc7b403b580>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known')': /session/heartbeat?requestId=a9e225d3-9710-4e5e-8942-0ad9a24cba3c&request_guid=79604c73-abeb-474a-8f11-0122205ad7b0\n",
      "2022-12-12 00:02:58.104 WARNING snowflake.connector.vendored.urllib3.connectionpool: Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<snowflake.connector.vendored.urllib3.connection.HTTPSConnection object at 0x7fc7a14e55e0>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known')': /session/heartbeat?requestId=a9e225d3-9710-4e5e-8942-0ad9a24cba3c&request_guid=c1a4d112-1de8-44fb-b4c9-4822d6bd79c2\n",
      "2022-12-12 00:35:42.089 WARNING snowflake.connector.vendored.urllib3.connectionpool: Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<snowflake.connector.vendored.urllib3.connection.HTTPSConnection object at 0x7fc7b300e400>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known')': /session/heartbeat?requestId=a9e225d3-9710-4e5e-8942-0ad9a24cba3c&request_guid=d200147c-f239-4528-971f-621cd5b16e81\n",
      "2022-12-12 00:52:53.148 WARNING snowflake.connector.vendored.urllib3.connectionpool: Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<snowflake.connector.vendored.urllib3.connection.HTTPSConnection object at 0x7fc7b3085b20>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known')': /session/heartbeat?requestId=a9e225d3-9710-4e5e-8942-0ad9a24cba3c&request_guid=f622d377-7c02-4171-9c65-a8969e09c134\n",
      "2022-12-12 01:27:41.030 WARNING snowflake.connector.vendored.urllib3.connectionpool: Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<snowflake.connector.vendored.urllib3.connection.HTTPSConnection object at 0x7fc7b3e07820>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known')': /session/heartbeat?requestId=a9e225d3-9710-4e5e-8942-0ad9a24cba3c&request_guid=b3306d56-758c-424b-9af1-d5deec3f1798\n",
      "2022-12-12 01:45:46.112 WARNING snowflake.connector.vendored.urllib3.connectionpool: Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<snowflake.connector.vendored.urllib3.connection.HTTPSConnection object at 0x7fc7b3e07730>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known')': /session/heartbeat?requestId=a9e225d3-9710-4e5e-8942-0ad9a24cba3c&request_guid=bcdadfb5-ab59-4ff2-812a-d001a0a99d1c\n",
      "2022-12-12 02:16:40.217 WARNING snowflake.connector.vendored.urllib3.connectionpool: Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<snowflake.connector.vendored.urllib3.connection.HTTPSConnection object at 0x7fc7b3085e50>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known')': /session/heartbeat?requestId=a9e225d3-9710-4e5e-8942-0ad9a24cba3c&request_guid=52dee693-be96-4acb-a047-353a366967c5\n",
      "2022-12-12 02:32:38.763 WARNING snowflake.connector.vendored.urllib3.connectionpool: Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<snowflake.connector.vendored.urllib3.connection.HTTPSConnection object at 0x7fc7b300e400>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known')': /session/heartbeat?requestId=a9e225d3-9710-4e5e-8942-0ad9a24cba3c&request_guid=f90c25f0-5254-4487-abb7-4c4ec8d7623c\n",
      "2022-12-12 02:49:08.832 WARNING snowflake.connector.vendored.urllib3.connectionpool: Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<snowflake.connector.vendored.urllib3.connection.HTTPSConnection object at 0x7fc7a14e5730>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known')': /session/heartbeat?requestId=a9e225d3-9710-4e5e-8942-0ad9a24cba3c&request_guid=82aaffd4-b524-4e3a-9a7b-aed1d970b7a9\n",
      "2022-12-12 03:24:09.214 WARNING snowflake.connector.vendored.urllib3.connectionpool: Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<snowflake.connector.vendored.urllib3.connection.HTTPSConnection object at 0x7fc7b403beb0>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known')': /session/heartbeat?requestId=a9e225d3-9710-4e5e-8942-0ad9a24cba3c&request_guid=026afee2-d3a7-4ea0-a8ef-bd3ad6ebfc60\n",
      "2022-12-12 03:41:28.234 WARNING snowflake.connector.vendored.urllib3.connectionpool: Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<snowflake.connector.vendored.urllib3.connection.HTTPSConnection object at 0x7fc7b2ddd8e0>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known')': /session/heartbeat?requestId=a9e225d3-9710-4e5e-8942-0ad9a24cba3c&request_guid=a4931dd1-e4ec-46e3-96a3-63d8f04eb273\n",
      "2022-12-12 04:14:10.205 WARNING snowflake.connector.vendored.urllib3.connectionpool: Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<snowflake.connector.vendored.urllib3.connection.HTTPSConnection object at 0x7fc7b3199f70>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known')': /session/heartbeat?requestId=a9e225d3-9710-4e5e-8942-0ad9a24cba3c&request_guid=3541ba10-fafd-4e3e-8348-e634b23ea509\n",
      "2022-12-12 04:31:57.224 WARNING snowflake.connector.vendored.urllib3.connectionpool: Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<snowflake.connector.vendored.urllib3.connection.HTTPSConnection object at 0x7fc7b3e07670>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known')': /session/heartbeat?requestId=a9e225d3-9710-4e5e-8942-0ad9a24cba3c&request_guid=4f1067c3-8846-4c82-b17d-36c089fba15c\n",
      "2022-12-12 04:49:51.159 WARNING snowflake.connector.vendored.urllib3.connectionpool: Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<snowflake.connector.vendored.urllib3.connection.HTTPSConnection object at 0x7fc7b2dddd30>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known')': /session/heartbeat?requestId=a9e225d3-9710-4e5e-8942-0ad9a24cba3c&request_guid=407f1ced-f9f1-42c1-9ef1-90f947f0a22e\n",
      "2022-12-12 05:21:17.368 WARNING snowflake.connector.vendored.urllib3.connectionpool: Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<snowflake.connector.vendored.urllib3.connection.HTTPSConnection object at 0x7fc7b31eaca0>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known')': /session/heartbeat?requestId=a9e225d3-9710-4e5e-8942-0ad9a24cba3c&request_guid=20b971e4-59c1-48ef-b227-c75586cc5759\n",
      "2022-12-12 05:21:21.389 WARNING snowflake.connector.vendored.urllib3.connectionpool: Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<snowflake.connector.vendored.urllib3.connection.HTTPSConnection object at 0x7fc7a14e5700>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known')': /session/heartbeat?requestId=a9e225d3-9710-4e5e-8942-0ad9a24cba3c&request_guid=1ce4d777-390f-44d6-bbc1-2352c9d146d5\n",
      "2022-12-12 05:37:24.899 WARNING snowflake.connector.vendored.urllib3.connectionpool: Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<snowflake.connector.vendored.urllib3.connection.HTTPSConnection object at 0x7fc7b2705820>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known')': /session/heartbeat?requestId=a9e225d3-9710-4e5e-8942-0ad9a24cba3c&request_guid=72b14a9c-6eff-4efa-ac79-b1921b50f194\n",
      "2022-12-12 05:53:15.968 WARNING snowflake.connector.vendored.urllib3.connectionpool: Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<snowflake.connector.vendored.urllib3.connection.HTTPSConnection object at 0x7fc7b3085580>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known')': /session/heartbeat?requestId=a9e225d3-9710-4e5e-8942-0ad9a24cba3c&request_guid=ec16319e-d1fd-49f5-b9c3-154c9ec478c7\n",
      "2022-12-12 06:09:08.966 WARNING snowflake.connector.vendored.urllib3.connectionpool: Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<snowflake.connector.vendored.urllib3.connection.HTTPSConnection object at 0x7fc7b3e07970>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known')': /session/heartbeat?requestId=a9e225d3-9710-4e5e-8942-0ad9a24cba3c&request_guid=7f171dee-f817-4ec6-96d8-513420ba7374\n",
      "2022-12-12 06:25:03.915 WARNING snowflake.connector.vendored.urllib3.connectionpool: Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<snowflake.connector.vendored.urllib3.connection.HTTPSConnection object at 0x7fc7b3e07700>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known')': /session/heartbeat?requestId=a9e225d3-9710-4e5e-8942-0ad9a24cba3c&request_guid=7447761e-7031-47cd-a327-c55a19fb4aed\n",
      "2022-12-12 06:41:43.915 WARNING snowflake.connector.vendored.urllib3.connectionpool: Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<snowflake.connector.vendored.urllib3.connection.HTTPSConnection object at 0x7fc7b3ac3910>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known')': /session/heartbeat?requestId=a9e225d3-9710-4e5e-8942-0ad9a24cba3c&request_guid=19b72b8d-51e8-4016-8a52-291178baf5b2\n",
      "2022-12-12 07:15:30.995 WARNING snowflake.connector.vendored.urllib3.connectionpool: Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<snowflake.connector.vendored.urllib3.connection.HTTPSConnection object at 0x7fc7b3e07b50>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known')': /session/heartbeat?requestId=a9e225d3-9710-4e5e-8942-0ad9a24cba3c&request_guid=1974310e-9a7a-45c8-a8ce-eead3b210942\n",
      "2022-12-12 07:32:12.984 WARNING snowflake.connector.vendored.urllib3.connectionpool: Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<snowflake.connector.vendored.urllib3.connection.HTTPSConnection object at 0x7fc7b3e07670>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known')': /session/heartbeat?requestId=a9e225d3-9710-4e5e-8942-0ad9a24cba3c&request_guid=cc2669fa-9dab-41c8-9e91-f68610e70d7f\n",
      "2022-12-12 08:04:23.525 WARNING snowflake.connector.vendored.urllib3.connectionpool: Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<snowflake.connector.vendored.urllib3.connection.HTTPSConnection object at 0x7fc7b307a2b0>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known')': /session/heartbeat?requestId=a9e225d3-9710-4e5e-8942-0ad9a24cba3c&request_guid=3da1b576-771f-4b2b-849d-b83b2ca2c18f\n",
      "2022-12-12 08:21:05.486 WARNING snowflake.connector.vendored.urllib3.connectionpool: Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<snowflake.connector.vendored.urllib3.connection.HTTPSConnection object at 0x7fc7b30858b0>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known')': /session/heartbeat?requestId=a9e225d3-9710-4e5e-8942-0ad9a24cba3c&request_guid=1fd50505-a427-4f4c-96ce-ad8a8f05220e\n",
      "2022-12-12 08:38:51.570 WARNING snowflake.connector.vendored.urllib3.connectionpool: Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<snowflake.connector.vendored.urllib3.connection.HTTPSConnection object at 0x7fc7b31c0a60>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known')': /session/heartbeat?requestId=a9e225d3-9710-4e5e-8942-0ad9a24cba3c&request_guid=8c6e9d1e-33b6-474a-963e-6ebec7cdcdf3\n",
      "2022-12-12 09:11:13.492 WARNING snowflake.connector.vendored.urllib3.connectionpool: Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<snowflake.connector.vendored.urllib3.connection.HTTPSConnection object at 0x7fc7a14e52b0>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known')': /session/heartbeat?requestId=a9e225d3-9710-4e5e-8942-0ad9a24cba3c&request_guid=8c491bfd-f8ca-4d0f-8111-0f01b19942e8\n",
      "2022-12-12 09:28:54.089 WARNING snowflake.connector.vendored.urllib3.connectionpool: Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<snowflake.connector.vendored.urllib3.connection.HTTPSConnection object at 0x7fc7b31c09d0>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known')': /session/heartbeat?requestId=a9e225d3-9710-4e5e-8942-0ad9a24cba3c&request_guid=69f5f4ab-dfa4-4054-aedf-5c4599e251e8\n",
      "2022-12-12 10:01:34.116 WARNING snowflake.connector.vendored.urllib3.connectionpool: Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<snowflake.connector.vendored.urllib3.connection.HTTPSConnection object at 0x7fc7a14d0df0>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known')': /session/heartbeat?requestId=a9e225d3-9710-4e5e-8942-0ad9a24cba3c&request_guid=41f53d9d-230d-43dd-a632-6457799808fd\n",
      "2022-12-12 10:19:39.080 WARNING snowflake.connector.vendored.urllib3.connectionpool: Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<snowflake.connector.vendored.urllib3.connection.HTTPSConnection object at 0x7fc7b3e07160>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known')': /session/heartbeat?requestId=a9e225d3-9710-4e5e-8942-0ad9a24cba3c&request_guid=b57bc87d-53d5-4965-8875-2e3dfdea9411\n",
      "2022-12-12 10:52:14.171 WARNING snowflake.connector.vendored.urllib3.connectionpool: Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<snowflake.connector.vendored.urllib3.connection.HTTPSConnection object at 0x7fc7b3e07820>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known')': /session/heartbeat?requestId=a9e225d3-9710-4e5e-8942-0ad9a24cba3c&request_guid=74154e13-6e3c-47a4-8a49-1256d25b60cb\n",
      "2022-12-12 11:09:51.162 WARNING snowflake.connector.vendored.urllib3.connectionpool: Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<snowflake.connector.vendored.urllib3.connection.HTTPSConnection object at 0x7fc7d1635280>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known')': /session/heartbeat?requestId=a9e225d3-9710-4e5e-8942-0ad9a24cba3c&request_guid=def942c4-8a84-4994-bc7a-f024948a418b\n",
      "2022-12-12 11:18:09.336 WARNING snowflake.connector.vendored.urllib3.connectionpool: Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<snowflake.connector.vendored.urllib3.connection.HTTPSConnection object at 0x7fc7b3a4d1c0>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known')': /session/heartbeat?requestId=a9e225d3-9710-4e5e-8942-0ad9a24cba3c&request_guid=8a8ce4cd-8b32-4340-bca6-8fe50e0d1f9e\n",
      "2022-12-12 11:33:46.097 WARNING snowflake.connector.vendored.urllib3.connectionpool: Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<snowflake.connector.vendored.urllib3.connection.HTTPSConnection object at 0x7fc7b3199730>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known')': /session/heartbeat?requestId=a9e225d3-9710-4e5e-8942-0ad9a24cba3c&request_guid=238eca5c-070c-40d4-8f5e-a0bfd501a052\n",
      "2022-12-12 11:33:47.116 WARNING snowflake.connector.vendored.urllib3.connectionpool: Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<snowflake.connector.vendored.urllib3.connection.HTTPSConnection object at 0x7fc7b300ecd0>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known')': /session/heartbeat?requestId=a9e225d3-9710-4e5e-8942-0ad9a24cba3c&request_guid=08c17a06-18a1-4e41-8bd3-3dc0440fccfb\n",
      "2022-12-12 11:33:49.135 WARNING snowflake.connector.vendored.urllib3.connectionpool: Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<snowflake.connector.vendored.urllib3.connection.HTTPSConnection object at 0x7fc7d16352b0>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known')': /session/heartbeat?requestId=a9e225d3-9710-4e5e-8942-0ad9a24cba3c&request_guid=4c303e0a-261b-46d8-83b2-bc8fb049173e\n",
      "2022-12-12 11:51:07.976 WARNING snowflake.connector.vendored.urllib3.connectionpool: Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<snowflake.connector.vendored.urllib3.connection.HTTPSConnection object at 0x7fc7b3e07880>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known')': /session/heartbeat?requestId=a9e225d3-9710-4e5e-8942-0ad9a24cba3c&request_guid=b66e47aa-54cb-477f-82bd-7859b1f49655\n",
      "2022-12-12 11:51:10.989 WARNING snowflake.connector.vendored.urllib3.connectionpool: Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<snowflake.connector.vendored.urllib3.connection.HTTPSConnection object at 0x7fc7b3e07310>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known')': /session/heartbeat?requestId=a9e225d3-9710-4e5e-8942-0ad9a24cba3c&request_guid=62a60d53-12af-4d1f-b189-f84e20604c05\n",
      "2022-12-12 11:51:17.000 WARNING snowflake.connector.vendored.urllib3.connectionpool: Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<snowflake.connector.vendored.urllib3.connection.HTTPSConnection object at 0x7fc7b3085dc0>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known')': /session/heartbeat?requestId=a9e225d3-9710-4e5e-8942-0ad9a24cba3c&request_guid=b11935a4-39b0-4960-8f0f-98e049f66170\n",
      "2022-12-12 12:07:49.060 WARNING snowflake.connector.vendored.urllib3.connectionpool: Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<snowflake.connector.vendored.urllib3.connection.HTTPSConnection object at 0x7fc7b31c0ca0>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known')': /session/heartbeat?requestId=a9e225d3-9710-4e5e-8942-0ad9a24cba3c&request_guid=42aa594b-be02-499c-988d-347a41fa84fd\n",
      "2022-12-12 12:07:53.080 WARNING snowflake.connector.vendored.urllib3.connectionpool: Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<snowflake.connector.vendored.urllib3.connection.HTTPSConnection object at 0x7fc7b2d99d30>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known')': /session/heartbeat?requestId=a9e225d3-9710-4e5e-8942-0ad9a24cba3c&request_guid=8ee1c5ff-4aef-43e1-b06d-7922bd5e61bc\n",
      "2022-12-12 12:25:42.953 WARNING snowflake.connector.vendored.urllib3.connectionpool: Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<snowflake.connector.vendored.urllib3.connection.HTTPSConnection object at 0x7fc7b31c0cd0>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known')': /session/heartbeat?requestId=a9e225d3-9710-4e5e-8942-0ad9a24cba3c&request_guid=c8ec65ae-77b3-4514-be42-b1f5fa4512b5\n",
      "2022-12-12 12:41:32.954 WARNING snowflake.connector.vendored.urllib3.connectionpool: Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<snowflake.connector.vendored.urllib3.connection.HTTPSConnection object at 0x7fc7a14d0a60>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known')': /session/heartbeat?requestId=a9e225d3-9710-4e5e-8942-0ad9a24cba3c&request_guid=04ea69a7-16bc-40c1-91a6-74230c6f92b8\n",
      "2022-12-12 12:59:24.903 WARNING snowflake.connector.vendored.urllib3.connectionpool: Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<snowflake.connector.vendored.urllib3.connection.HTTPSConnection object at 0x7fc7b3e078e0>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known')': /session/heartbeat?requestId=a9e225d3-9710-4e5e-8942-0ad9a24cba3c&request_guid=f9df84f2-592d-4f84-88b3-7bb73c8137b4\n",
      "2022-12-12 12:59:40.919 WARNING snowflake.connector.vendored.urllib3.connectionpool: Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<snowflake.connector.vendored.urllib3.connection.HTTPSConnection object at 0x7fc7b3e07880>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known')': /session/heartbeat?requestId=a9e225d3-9710-4e5e-8942-0ad9a24cba3c&request_guid=866a2c94-280f-418e-bf6e-5d9c07dc6c55\n",
      "2022-12-12 12:59:56.945 WARNING snowflake.connector.vendored.urllib3.connectionpool: Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<snowflake.connector.vendored.urllib3.connection.HTTPSConnection object at 0x7fc7b31eab50>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known')': /session/heartbeat?requestId=a9e225d3-9710-4e5e-8942-0ad9a24cba3c&request_guid=9ef1db9f-73c3-4d1b-9e51-b5cab6c839cf\n",
      "2022-12-12 13:00:12.960 WARNING snowflake.connector.vendored.urllib3.connectionpool: Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<snowflake.connector.vendored.urllib3.connection.HTTPSConnection object at 0x7fc7b300e040>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known')': /session/heartbeat?requestId=a9e225d3-9710-4e5e-8942-0ad9a24cba3c&request_guid=ddef94f8-1bf6-498d-92b9-ab34cdc36a7f\n",
      "2022-12-12 13:00:15.979 WARNING snowflake.connector.vendored.urllib3.connectionpool: Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<snowflake.connector.vendored.urllib3.connection.HTTPSConnection object at 0x7fc7b2d993a0>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known')': /session/heartbeat?requestId=a9e225d3-9710-4e5e-8942-0ad9a24cba3c&request_guid=691c53c4-3981-4dc1-b24b-4891122d3b4b\n",
      "2022-12-12 13:00:23.000 WARNING snowflake.connector.vendored.urllib3.connectionpool: Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<snowflake.connector.vendored.urllib3.connection.HTTPSConnection object at 0x7fc7b2d998b0>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known')': /session/heartbeat?requestId=a9e225d3-9710-4e5e-8942-0ad9a24cba3c&request_guid=13e7dd15-80bb-48ed-9bd9-7e2cb65f66ef\n",
      "2022-12-12 13:32:02.571 WARNING snowflake.connector.vendored.urllib3.connectionpool: Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<snowflake.connector.vendored.urllib3.connection.HTTPSConnection object at 0x7fc7a14e5b20>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known')': /session/heartbeat?requestId=a9e225d3-9710-4e5e-8942-0ad9a24cba3c&request_guid=40655f5e-d170-431b-b3a1-65a9da46e33a\n",
      "2022-12-12 13:32:06.591 WARNING snowflake.connector.vendored.urllib3.connectionpool: Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<snowflake.connector.vendored.urllib3.connection.HTTPSConnection object at 0x7fc7b403b850>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known')': /session/heartbeat?requestId=a9e225d3-9710-4e5e-8942-0ad9a24cba3c&request_guid=27a114f8-e786-4291-b584-718a1b2f154a\n",
      "2022-12-12 13:47:12.201 WARNING snowflake.connector.vendored.urllib3.connectionpool: Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<snowflake.connector.vendored.urllib3.connection.HTTPSConnection object at 0x7fc7b3e07340>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known')': /session/heartbeat?requestId=a9e225d3-9710-4e5e-8942-0ad9a24cba3c&request_guid=4867b10f-1e4e-4b8e-8148-aa63d06a4585\n",
      "2022-12-12 14:02:55.093 WARNING snowflake.connector.vendored.urllib3.connectionpool: Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<snowflake.connector.vendored.urllib3.connection.HTTPSConnection object at 0x7fc7b3e07dc0>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known')': /session/heartbeat?requestId=a9e225d3-9710-4e5e-8942-0ad9a24cba3c&request_guid=dc58c252-416f-4a3e-8ac0-e26f1c48b337\n",
      "2022-12-12 14:37:05.849 WARNING snowflake.connector.vendored.urllib3.connectionpool: Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<snowflake.connector.vendored.urllib3.connection.HTTPSConnection object at 0x7fc7a14d0df0>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known')': /session/heartbeat?requestId=a9e225d3-9710-4e5e-8942-0ad9a24cba3c&request_guid=a6a0eeac-efc3-4c39-a9d9-e5d32ca107cf\n",
      "2022-12-12 14:54:40.004 WARNING snowflake.connector.vendored.urllib3.connectionpool: Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<snowflake.connector.vendored.urllib3.connection.HTTPSConnection object at 0x7fc7b31c0a60>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known')': /session/heartbeat?requestId=a9e225d3-9710-4e5e-8942-0ad9a24cba3c&request_guid=563f49b0-3eb1-45ab-b893-0788b5f4dbdb\n",
      "2022-12-12 15:25:43.184 WARNING snowflake.connector.vendored.urllib3.connectionpool: Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<snowflake.connector.vendored.urllib3.connection.HTTPSConnection object at 0x7fc7b31c0c10>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known')': /session/heartbeat?requestId=a9e225d3-9710-4e5e-8942-0ad9a24cba3c&request_guid=09c7242b-e297-4290-a2f8-ed18454cadeb\n",
      "2022-12-12 15:41:03.773 WARNING snowflake.connector.vendored.urllib3.connectionpool: Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<snowflake.connector.vendored.urllib3.connection.HTTPSConnection object at 0x7fc7b3085070>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known')': /session/heartbeat?requestId=a9e225d3-9710-4e5e-8942-0ad9a24cba3c&request_guid=dee7e56b-5b9f-4fff-9024-034dfea7e0b2\n",
      "2022-12-12 15:56:58.791 WARNING snowflake.connector.vendored.urllib3.connectionpool: Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<snowflake.connector.vendored.urllib3.connection.HTTPSConnection object at 0x7fc7b3e075e0>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known')': /session/heartbeat?requestId=a9e225d3-9710-4e5e-8942-0ad9a24cba3c&request_guid=561411d8-9672-4d65-96b9-f98b8c178c11\n",
      "2022-12-12 16:30:01.742 WARNING snowflake.connector.vendored.urllib3.connectionpool: Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<snowflake.connector.vendored.urllib3.connection.HTTPSConnection object at 0x7fc7b3e07430>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known')': /session/heartbeat?requestId=a9e225d3-9710-4e5e-8942-0ad9a24cba3c&request_guid=97fc9b41-eeb6-4290-89a3-21cebb9a8437\n",
      "2022-12-12 16:45:21.706 WARNING snowflake.connector.vendored.urllib3.connectionpool: Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<snowflake.connector.vendored.urllib3.connection.HTTPSConnection object at 0x7fc7b31ea9a0>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known')': /session/heartbeat?requestId=a9e225d3-9710-4e5e-8942-0ad9a24cba3c&request_guid=eb4672dd-9593-4580-b18a-c1575548c664\n",
      "2022-12-12 17:17:35.761 WARNING snowflake.connector.vendored.urllib3.connectionpool: Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<snowflake.connector.vendored.urllib3.connection.HTTPSConnection object at 0x7fc7b300e040>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known')': /session/heartbeat?requestId=a9e225d3-9710-4e5e-8942-0ad9a24cba3c&request_guid=03bdac8c-1841-4393-8f21-3c7839164aca\n",
      "2022-12-12 17:35:37.743 WARNING snowflake.connector.vendored.urllib3.connectionpool: Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<snowflake.connector.vendored.urllib3.connection.HTTPSConnection object at 0x7fc7b2d99520>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known')': /session/heartbeat?requestId=a9e225d3-9710-4e5e-8942-0ad9a24cba3c&request_guid=0f76f051-e58d-479d-93cb-7246e55afb74\n",
      "2022-12-12 17:35:40.766 WARNING snowflake.connector.vendored.urllib3.connectionpool: Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<snowflake.connector.vendored.urllib3.connection.HTTPSConnection object at 0x7fc7b2ddd370>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known')': /session/heartbeat?requestId=a9e225d3-9710-4e5e-8942-0ad9a24cba3c&request_guid=f21dd644-5014-4b97-8bdb-6e863b63fa03\n",
      "2022-12-12 17:52:05.691 WARNING snowflake.connector.vendored.urllib3.connectionpool: Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<snowflake.connector.vendored.urllib3.connection.HTTPSConnection object at 0x7fc7b2d99280>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known')': /session/heartbeat?requestId=a9e225d3-9710-4e5e-8942-0ad9a24cba3c&request_guid=b3f2f5e1-0be3-49c2-babb-35883d215445\n",
      "2022-12-12 18:09:07.737 WARNING snowflake.connector.vendored.urllib3.connectionpool: Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<snowflake.connector.vendored.urllib3.connection.HTTPSConnection object at 0x7fc7b321ff10>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known')': /session/heartbeat?requestId=a9e225d3-9710-4e5e-8942-0ad9a24cba3c&request_guid=d5f86562-97aa-4ca1-8edc-3a1d25331232\n",
      "2022-12-12 18:43:16.821 WARNING snowflake.connector.vendored.urllib3.connectionpool: Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<snowflake.connector.vendored.urllib3.connection.HTTPSConnection object at 0x7fc7b3e07730>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known')': /session/heartbeat?requestId=a9e225d3-9710-4e5e-8942-0ad9a24cba3c&request_guid=c19eaff7-bfd4-4e53-975b-e3ff411fe43f\n",
      "2022-12-12 18:43:32.838 WARNING snowflake.connector.vendored.urllib3.connectionpool: Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<snowflake.connector.vendored.urllib3.connection.HTTPSConnection object at 0x7fc7b3e07970>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known')': /session/heartbeat?requestId=a9e225d3-9710-4e5e-8942-0ad9a24cba3c&request_guid=7ca62eab-3ad4-4155-a053-cf0e11ff831a\n",
      "2022-12-12 18:43:45.856 WARNING snowflake.connector.vendored.urllib3.connectionpool: Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<snowflake.connector.vendored.urllib3.connection.HTTPSConnection object at 0x7fc7b3085dc0>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known')': /session/heartbeat?requestId=a9e225d3-9710-4e5e-8942-0ad9a24cba3c&request_guid=736a3093-9c3a-436b-85a0-881f394cce5a\n",
      "2022-12-12 18:43:54.873 WARNING snowflake.connector.vendored.urllib3.connectionpool: Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<snowflake.connector.vendored.urllib3.connection.HTTPSConnection object at 0x7fc7b31b5df0>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known')': /session/heartbeat?requestId=a9e225d3-9710-4e5e-8942-0ad9a24cba3c&request_guid=0bdfef82-893b-43c5-b425-5fad0fef452f\n",
      "2022-12-12 18:43:58.897 WARNING snowflake.connector.vendored.urllib3.connectionpool: Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<snowflake.connector.vendored.urllib3.connection.HTTPSConnection object at 0x7fc7b2ddda60>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known')': /session/heartbeat?requestId=a9e225d3-9710-4e5e-8942-0ad9a24cba3c&request_guid=639bd724-9aaa-468b-9e1e-524572cd76c5\n",
      "2022-12-12 18:44:01.917 WARNING snowflake.connector.vendored.urllib3.connectionpool: Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<snowflake.connector.vendored.urllib3.connection.HTTPSConnection object at 0x7fc7a14d0370>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known')': /session/heartbeat?requestId=a9e225d3-9710-4e5e-8942-0ad9a24cba3c&request_guid=393cbbe9-e3c6-4a94-a438-dba492280b1e\n",
      "2022-12-12 18:44:09.931 WARNING snowflake.connector.vendored.urllib3.connectionpool: Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<snowflake.connector.vendored.urllib3.connection.HTTPSConnection object at 0x7fc7b3085070>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known')': /session/heartbeat?requestId=a9e225d3-9710-4e5e-8942-0ad9a24cba3c&request_guid=3e288307-2e69-4281-a130-2ffdcc9cfcaf\n",
      "2022-12-12 18:59:25.563 WARNING snowflake.connector.vendored.urllib3.connectionpool: Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<snowflake.connector.vendored.urllib3.connection.HTTPSConnection object at 0x7fc7b3e072e0>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known')': /session/heartbeat?requestId=a9e225d3-9710-4e5e-8942-0ad9a24cba3c&request_guid=a74a017d-1b4b-46a0-9935-2aa2e6736dca\n",
      "2022-12-12 18:59:30.589 WARNING snowflake.connector.vendored.urllib3.connectionpool: Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<snowflake.connector.vendored.urllib3.connection.HTTPSConnection object at 0x7fc7b3b5ce50>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known')': /session/heartbeat?requestId=a9e225d3-9710-4e5e-8942-0ad9a24cba3c&request_guid=b11ed5ba-0afc-4f8b-8e2f-1af43c775f4c\n",
      "2022-12-12 19:14:36.085 WARNING snowflake.connector.vendored.urllib3.connectionpool: Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<snowflake.connector.vendored.urllib3.connection.HTTPSConnection object at 0x7fc7c0f55fa0>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known')': /session/heartbeat?requestId=a9e225d3-9710-4e5e-8942-0ad9a24cba3c&request_guid=7603767a-967e-486d-b982-bca98df76732\n",
      "2022-12-12 19:14:43.100 WARNING snowflake.connector.vendored.urllib3.connectionpool: Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<snowflake.connector.vendored.urllib3.connection.HTTPSConnection object at 0x7fc7b2d99910>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known')': /session/heartbeat?requestId=a9e225d3-9710-4e5e-8942-0ad9a24cba3c&request_guid=f3cdcc3c-b402-4b6e-a1d4-839b49d305f1\n",
      "2022-12-12 19:14:44.126 WARNING snowflake.connector.vendored.urllib3.connectionpool: Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<snowflake.connector.vendored.urllib3.connection.HTTPSConnection object at 0x7fc7b2dd8ca0>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known')': /session/heartbeat?requestId=a9e225d3-9710-4e5e-8942-0ad9a24cba3c&request_guid=54e59901-871c-44bf-aaf5-f40760b37251\n",
      "2022-12-12 19:14:47.150 WARNING snowflake.connector.vendored.urllib3.connectionpool: Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<snowflake.connector.vendored.urllib3.connection.HTTPSConnection object at 0x7fc7a14e55e0>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known')': /session/heartbeat?requestId=a9e225d3-9710-4e5e-8942-0ad9a24cba3c&request_guid=e9acb8a8-e018-4201-9428-020bedef2404\n",
      "2022-12-12 19:28:27.787 WARNING snowflake.connector.vendored.urllib3.connectionpool: Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<snowflake.connector.vendored.urllib3.connection.HTTPSConnection object at 0x7fc7b31ea790>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known')': /session/heartbeat?requestId=a9e225d3-9710-4e5e-8942-0ad9a24cba3c&request_guid=0de5db63-bb9a-44fe-bb56-ae825ca3fbb6\n",
      "2022-12-14 07:56:56.837 WARNING snowflake.connector.vendored.urllib3.connectionpool: Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'SSLError(SSLError(\"bad handshake: SysCallError(60, 'ETIMEDOUT')\"))': /session/heartbeat?requestId=cfb34fb9-2cf7-42a7-84f5-c97d1b3fdfe4&request_guid=f8b7423b-9e50-4433-95d2-f0eb3a275b44\n"
     ]
    }
   ],
   "source": [
    "dat[dat['STATUS']=='scroll']"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 15,
   "metadata": {},
   "outputs": [
    {
     "data": {
      "text/plain": [
       "'7852ed9a-8e57-42ac-af73-cf639f8f3f39'"
      ]
     },
     "execution_count": 15,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "release_dict[release_chk]"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": [
    "\n",
    "def cacherecos(_s, influ_chk, release_dict, release_chk, max_recs):\n",
    "    \n",
    "    \n",
    "\n",
    "    data = []\n",
    "    for val in range(0,max_recs,1):\n",
    "        try:\n",
    "            img = Image.open(urlopen(drops.iloc[val]['IMAGEURL']))\n",
    "            caption = drops.iloc[val]['STATUS'] +' | ' + drops.iloc[val]['OS_MERCHANT'] + ' | ' + drops.iloc[val]['PRODUCT_TITLE'] + ' | Price : ${:.2f}'.format(drops.iloc[val]['PRICE']) + ' | % Discount : ' + str(drops.iloc[val]['DISCOUNT_PERCENTAGE']*100) + '% | Gross Margin : {:.2%}'.format(drops.iloc[val]['PRODUCT_GROSS_MARGIN'])\n",
    "            product_id = drops.iloc[val]['PRODUCT_ID']\n",
    "            if drops.iloc[val]['STATUS'] == 'drop':\n",
    "                try:\n",
    "                    description = json2html.convert(json =json.loads(drops.iloc[val]['COLLAB_METADATA']))\n",
    "                except:\n",
    "                    description = '<b>DROP</b>'\n",
    "            else:\n",
    "                description = '<b>SCROLL</b>'\n",
    "        except:\n",
    "            pass\n",
    "        data.append((img, caption, product_id, description))\n",
    "\n",
    "    return [data, drops]"
   ]
  }
 ],
 "metadata": {
  "language_info": {
   "name": "python"
  },
  "orig_nbformat": 4
 },
 "nbformat": 4,
 "nbformat_minor": 2
}
